title: Xiaoyong Pan 
#tagline:          A short tagline
#description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url: http://xypan1232.github.io

# Owner/author information
owner:
  name:           Xiaoyong Pan
  avatar:         
#  bio:
  email:          xypan172436@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: xypan1232
  facebook:
  github: xypan1232
  linkedin: xypan1232
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_verify: "JW0gdx05xcJSQe6saaq67u_U1vgdfuh8OxrjS-fEuyQ"
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Team
    url: /team/
  - title: Publications
    url: /publications/
  - title: Experience
    url: /experience/
  - title: Software
    url: /software/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/New_York
future: true
pygments: true
#markdown: kramdown
markdown: redcarpet

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]


